/**
 * Seed content for a fresh database.
 *
 * Everything here is *starter* data pulled from the school's official material —
 * club names, objectives and teacher names are real; the picture placeholders in
 * /public/media stay until the real photos are uploaded from the admin studio
 * (Cloudinary) or a club's own console.
 */
import type { ResourceName } from "@/lib/types";

const media = (name: string) => `/media/${name}.svg`;

const clubs = [
  {
    id: "club-alssm",
    name: "ম্যাথ এন্ড সাইন্স ক্লাব",
    name_en: "Association Of Little Scientists And Math Maniacs",
    short_code: "ALSSM",
    slug: "alssm",
    motto: "কৌতূহল থেকে আবিষ্কার",
    tagline: "গণিত ও বিজ্ঞানের ভয় দূরে, অনুসন্ধানের আনন্দ কাছে",
    description:
      "গণিত ও বিজ্ঞানের ভয় দূর করা, কুইজ ও অলিম্পিয়াডের প্রস্তুতি এবং প্রতি বছর বিজ্ঞান মেলার আয়োজন — স্কুলের সবচেয়ে বড় ক্লাব।",
    history:
      "গণিত আর বিজ্ঞানকে বইয়ের বাইরে নিয়ে আসার ইচ্ছা থেকেই ক্লাবটির যাত্রা। নিয়মিত কুইজ, হাতে-কলমে পরীক্ষা ও বার্ষিক বিজ্ঞান মেলার আয়োজন করে ক্লাবটি এখন পুরো কালাই উপজেলার শিক্ষার্থীদের আকর্ষণের কেন্দ্র।",
    mission:
      "স্মৃতিনির্ভর পাঠ নয় — প্রশ্ন করা, পরীক্ষা করা আর নিজের হাতে আবিষ্কার করার অভ্যাস গড়ে তোলা।",
    objectives: [
      "গণিত ও বিজ্ঞানের ভয় দূর করা।",
      "গণিত ও বিজ্ঞানে দক্ষতা ও আগ্রহ বাড়ানো।",
      "গণিত ও বিজ্ঞানের মজার দিকগুলো শিক্ষার্থীদের কাছে তুলে ধরা।",
      "বইয়ের বাইরের বিজ্ঞান-জগতের সাথে শিক্ষার্থীদের পরিচয় করিয়ে দেওয়া।",
      "নিয়মিত কুইজ প্রতিযোগিতা ও বিজ্ঞান মেলার আয়োজন করা।",
      "অন্য শিক্ষা প্রতিষ্ঠানের শিক্ষার্থীদের আমন্ত্রণ জানিয়ে প্রতিযোগিতা আয়োজন।",
      "সদস্যদের প্রতি বছর গণিতসহ বিভিন্ন অলিম্পিয়াডে অংশগ্রহণের ব্যবস্থা করা।",
    ].join("\n"),
    accent: "#f59e0b",
    icon: "Atom",
    logo_url: media("club-science"),
    image_url: media("club-science"),
    cover_image_url: media("club-science-cover"),
    gallery_urls: [media("gallery-science-1"), media("gallery-science-2"), media("gallery-science-3"), media("gallery-science-4")].join("\n"),
    founded_year: 0,
    member_count: 0,
    meeting_day: "প্রতি বৃহস্পতিবার",
    meeting_time: "বিকাল ৪টা – ৫টা",
    meeting_place: "বিজ্ঞানাগার",
    coordinator: "মোঃ রহমতুল্লাহ পিকে",
    president: "",
    secretary: "",
    email: "science.club@okgs.info",
    subdomain: "alssm.okgs.info",
    domain: "https://alssm.okgs.info",
    facebook_url: "https://www.facebook.com/omarkgschool",
    club_folder: "clubs/alssm",
    join_info:
      "প্রতি বৃহস্পতিবার বিকেলে সরাসরি বিজ্ঞানাগারে আসুন, অথবা ক্লাবের সাধারণ সম্পাদকের কাছে নাম লেখান।",
    sort_order: 1,
  },
  {
    id: "club-aypg",
    name: "ল্যাংগুয়েজ ক্লাব",
    name_en: "Association Of Young Philologists And Grammarians",
    short_code: "AYPG",
    slug: "aypg",
    motto: "কথায় ভাব, লেখায় চিন্তা",
    tagline: "শুদ্ধ বাংলা আর সাবলীল ইংরেজির চর্চা",
    description:
      "শুদ্ধ বাংলা ও ইংরেজি ভাষার চর্চা, আবৃত্তি, উপস্থিত বক্তৃতা, বিতর্ক ও বইপড়া কর্মসূচি — ভাষাপ্রেমীদের ক্লাব।",
    history:
      "শুদ্ধ উচ্চারণ, বানান আর সাহিত্যপাঠের আনন্দ ছড়িয়ে দিতেই ক্লাবটি কাজ করছে। প্রতি বছর বাংলা ও ইংরেজি বিতর্ক প্রতিযোগিতা, আবৃত্তি উৎসব ও ভাষার মাসের আয়োজন ক্লাবটির পরিচিতি।",
    mission:
      "ভয়ভাঙা কথা বলার আত্মবিশ্বাস এবং নিজের ভাবনা লিখে ফেলার অভ্যাস তৈরি করা।",
    objectives: [
      "শুদ্ধ বাংলা ভাষা চর্চা করা।",
      "বাংলা ও ইংরেজিসহ দেশি-বিদেশি সাহিত্য চর্চা করা।",
      "দেশি-বিদেশি ভাষায় সাবলীলভাবে কথা বলার অভ্যাস গড়ে তোলা।",
      "Speaking English-এর পাশাপাশি উচ্চারণ, বানান ও ব্যাকরণ চর্চা করা।",
      "ভাষা সংক্রান্ত বইপড়া কর্মসূচি পরিচালনা করা।",
      "নিয়মিত কুইজ প্রতিযোগিতার আয়োজন করা।",
      "বাংলা ও ইংরেজি কবিতা আবৃত্তি ও উপস্থিত বক্তৃতার আয়োজন করা।",
      "প্রতি বছর বাংলা ও ইংরেজি বিতর্ক প্রতিযোগিতার আয়োজন করা।",
      "ভাষার মাসে বিশেষ প্রোগ্রাম আয়োজন করা।",
      "অন্য শিক্ষা প্রতিষ্ঠানকে আমন্ত্রণ জানিয়ে প্রতিযোগিতা আয়োজন করা।",
      "সদস্যদের প্রতি বছর বাংলা অলিম্পিয়াডে অংশগ্রহণের ব্যবস্থা করা।",
    ].join("\n"),
    accent: "#0d9488",
    icon: "BookOpen",
    logo_url: media("club-language"),
    image_url: media("club-language"),
    cover_image_url: media("club-language-cover"),
    gallery_urls: [media("gallery-language-1"), media("gallery-language-2")].join("\n"),
    founded_year: 0,
    member_count: 0,
    meeting_day: "প্রতি রবিবার",
    meeting_time: "সকাল ৯টা – ১০টা",
    meeting_place: "স্কুল পাঠাগার",
    coordinator: "মোছাঃ ফাতেমা আক্তার",
    email: "language.club@okgs.info",
    subdomain: "aypg.okgs.info",
    domain: "https://aypg.okgs.info",
    facebook_url: "https://www.facebook.com/omarkgschool",
    club_folder: "clubs/aypg",
    join_info: "পাঠাগারে নাম লেখান, অথবা শিক্ষকের কাছে নিজের লেখা একটি কবিতা বা গল্প জমা দিন।",
    sort_order: 2,
  },
  {
    id: "club-alpcg",
    name: "কম্পিউটার ক্লাব",
    name_en: "Association Of Little Programmers And Computer Geeks",
    short_code: "ALPCG",
    slug: "alpcg",
    motto: "Shikho · Banai · Bhago",
    tagline: "প্রোগ্রামিং, ওয়েব আর তথ্যপ্রযুক্তির হাতেখড়ি",
    description:
      "প্রোগ্রামিংয়ে হাতেখড়ি, ওয়েব ডেভেলপমেন্ট, কম্পিউটার কুইজ ও আইসিটি প্রতিযোগিতা — ভবিষ্যতের প্রোগ্রামারদের ক্লাব।",
    history:
      "ওয়েব ডেভেলপমেন্ট কনটেস্ট ও হাতে-কলমে আইসিটি কর্মশালার মধ্য দিয়ে ক্লাবটি শিক্ষার্থীদের প্রযুক্তির সাথে পরিচয় করিয়ে দিচ্ছে। স্কুলের নিজস্ব কম্পিউটার ল্যাবে ক্লাবের নিয়মিত সেশন হয়।",
    mission: "সব শিক্ষার্থীকে প্রযুক্তির ব্যবহারকারী নয়, নির্মাতা হিসেবে গড়ে তোলা।",
    objectives: [
      "কম্পিউটার চর্চার মাধ্যমে আইসিটিতে দক্ষ করে তোলা।",
      "তথ্য ও প্রযুক্তির সঠিক ধারণা দেওয়া।",
      "প্রোগ্রামিংয়ে হাতেখড়ি দেওয়া।",
      "নিয়মিত কম্পিউটার কুইজ ও প্রোগ্রামিং প্রতিযোগিতা আয়োজন।",
      "সার্চের মাধ্যমে যেকোনো তথ্য খুঁজে বের করার দক্ষতা অর্জন।",
      "অন্য শিক্ষা প্রতিষ্ঠানকে আমন্ত্রণ জানিয়ে প্রতিযোগিতা আয়োজন।",
      "সদস্যদের বিভিন্ন অলিম্পিয়াডে অংশগ্রহণ ও প্রশিক্ষণ দেওয়া।",
    ].join("\n"),
    accent: "#2563eb",
    icon: "Monitor",
    logo_url: media("club-computer"),
    image_url: media("club-computer"),
    cover_image_url: media("club-computer-cover"),
    gallery_urls: [media("gallery-computer-1"), media("gallery-computer-2")].join("\n"),
    founded_year: 0,
    member_count: 0,
    meeting_day: "প্রতি বুধবার",
    meeting_time: "বিকাল ৩টা – ৪টা",
    meeting_place: "কম্পিউটার ল্যাব",
    coordinator: "মোঃ মেহেরুল ইসলাম",
    email: "computer.club@okgs.info",
    subdomain: "alpcg.okgs.info",
    domain: "https://alpcg.okgs.info",
    facebook_url: "https://www.facebook.com/omarkgschool",
    club_folder: "clubs/alpcg",
    join_info: "কম্পিউটার ল্যাবে ক্লাবের সেশনে চলে আসুন — ফর্ম পূরণ করে সদস্য হোন।",
    sort_order: 3,
  },
  {
    id: "club-aygsm",
    name: "স্পোর্টিং ক্লাব",
    name_en: "Association Of Young Gymnastics And Sports Maniac",
    short_code: "AYGSM",
    slug: "aygsm",
    motto: "সুস্থ শরীর, প্রফুল্ল মন",
    tagline: "খেলাধুলার মাধ্যমে শৃঙ্খলা ও দলগত মানসিকতা",
    description:
      "মোবাইল আসক্তি থেকে দূরে রেখে খেলাধুলায় উৎসাহ, নিয়মিত ক্রীড়া প্রতিযোগিতা এবং জেলা-জাতীয় পর্যায়ে অংশগ্রহণের প্রস্তুতি।",
    history:
      "বার্ষিক ক্রীড়া প্রতিযোগিতা, ফুটবল, কাবাডি ও জিমন্যাস্টিকসের চর্চা নিয়ে ক্লাবটি বছরের পর বছর ধরে স্কুল দলকে প্রতিনিধিত্ব করছে।",
    mission: "খেলার মাঠকে শ্রেণিকক্ষের মতোই শেখার জায়গা বানানো।",
    objectives: [
      "মোবাইল/ফেসবুক/ভিডিও গেমসের আসক্তি থেকে মুক্ত করে খেলাধুলায় উৎসাহ দেওয়া।",
      "‘খেলাধুলার মাধ্যমে সুস্থ শরীর ও প্রফুল্ল মন’ — এই নীতিতে উদ্বুদ্ধ করা।",
      "খেলাধুলায় পারদর্শী শিক্ষার্থীদের আরও ভালো করতে উৎসাহ দেওয়া।",
      "নিয়মিত বিভিন্ন খেলাধুলার প্রতিযোগিতার আয়োজন করা।",
      "অন্য শিক্ষা প্রতিষ্ঠানকে আমন্ত্রণ জানিয়ে ক্রীড়া প্রতিযোগিতা আয়োজন।",
      "স্থানীয়, বিভাগীয় ও জাতীয় পর্যায়ে অংশগ্রহণ ও প্রশিক্ষণের ব্যবস্থা করা।",
    ].join("\n"),
    accent: "#dc2626",
    icon: "Trophy",
    logo_url: media("club-sports"),
    image_url: media("club-sports"),
    cover_image_url: media("club-sports-cover"),
    gallery_urls: [media("gallery-sports-1"), media("gallery-sports-2"), media("gallery-sports-3")].join("\n"),
    founded_year: 0,
    member_count: 0,
    meeting_day: "প্রতি শুক্রবার",
    meeting_time: "বিকাল ৪টা – ৬টা",
    meeting_place: "স্কুল মাঠ",
    coordinator: "মোঃ আবুল কালাম আজাদ",
    email: "sports.club@okgs.info",
    subdomain: "aygsm.okgs.info",
    domain: "https://aygsm.okgs.info",
    facebook_url: "https://www.facebook.com/omarkgschool",
    club_folder: "clubs/aygsm",
    join_info: "শুক্রবার বিকেলে মাঠে আসুন — খেলা দেখে বা খেলে দুই ভাবেই সদস্য হওয়া যায়।",
    sort_order: 4,
  },
  {
    id: "club-artds",
    name: "ART Debating Society",
    name_en: "ART Debating Society",
    short_code: "ARTDS",
    slug: "artds",
    motto: "যুক্তিই শক্তি",
    tagline: "বিতর্ক, উপস্থিত বক্তৃতা ও নেতৃত্বচর্চা",
    description:
      "যুক্তি, উপস্থাপন ও শালীনতার চর্চায় বিতর্ক — আন্তঃশ্রেণি ও আন্তঃস্কুল বিতর্ক প্রতিযোগিতা এবং মডেল ইউনাইটেড নেশনের মতো আয়োজন।",
    history:
      "বিতর্কের মঞ্চেই তৈরি হয় যুক্তি আর আত্মবিশ্বাস। ক্লাবটি আন্তঃশ্রেণি বিতর্ক, উপস্থিত বক্তৃতা ও বিতর্ক কর্মশালা নিয়মিত আয়োজন করে।",
    mission: "পক্ষে-বিপক্ষে ভাবতে শেখা — যুক্তি দিয়ে নিজের মত গড়ে তোলার অভ্যাস।",
    objectives: [
      "যুক্তিনির্ভর বিতর্কের চর্চা ও আন্তঃশ্রেণি প্রতিযোগিতা।",
      "উপস্থিত বক্তৃতা ও দলগত আলোচনার প্রশিক্ষণ।",
      "আন্তঃস্কুল বিতর্ক প্রতিযোগিতার আয়োজন ও অংশগ্রহণ।",
      "বক্তৃতা, সংসদীয় বিতর্ক ও মডেল ইউএন কর্মশালা।",
      "শালীন ভাষায় মতভেদ ও নেতৃত্বের চর্চা।",
    ].join("\n"),
    accent: "#7c3aed",
    icon: "MessagesSquare",
    logo_url: media("club-culture"),
    image_url: media("club-culture"),
    cover_image_url: media("club-culture-cover"),
    gallery_urls: [media("gallery-culture-1"), media("gallery-culture-2")].join("\n"),
    founded_year: 0,
    member_count: 0,
    meeting_day: "প্রতি সোমবার",
    meeting_time: "বিকাল ৪টা",
    meeting_place: "মিলনায়তন",
    coordinator: "মোছাঃ রোজিনা আক্তার",
    email: "debate.club@okgs.info",
    subdomain: "artds.okgs.info",
    domain: "https://artds.okgs.info",
    facebook_url: "https://www.facebook.com/omarkgschool",
    club_folder: "clubs/artds",
    join_info: "মিলনায়তনে সোমবারের সেশনে আসুন বা শিক্ষকের কাছে নাম লেখান।",
    sort_order: 5,
  },
];

const fairs = [
  {
    id: "fair-2026",
    name: "OKGS Science Fair 2026",
    name_en: "OKGS Science Fair 2026",
    slug: "science-fair-2026",
    edition: "২০২৬",
    tagline: "স্বপ্ন দেখো · পরীক্ষা করো · আবিষ্কার করো",
    description:
      "সমকালীন বিজ্ঞান ও প্রযুক্তির অগ্রযাত্রার সাথে শিক্ষার্থীদের মেলে ধরার জন্য ওমর কিন্ডারগার্টেন স্কুলের বার্ষিক বিজ্ঞান মেলা।",
    about:
      "বিজ্ঞান মেলার দিন শিক্ষার্থীদের হাতে-বানানো মডেল, রোবোটিক্স প্রকল্প, রসায়ন-পরীক্ষার ডেমো, পোস্টার ও প্রোগ্রামিং কাজ একসাথে প্রদর্শিত হবে। প্রতিটি ক্যাটাগরিতে বিচারকমণ্ডলী কঠোরভাবে স্কোর দেন, আর দিনের শেষে বিজয়ীদের জন্য পুরস্কার ও সনদ থাকে। আরএসভিপি ছাড়া দর্শনার্থীরাও ঘুরে দেখতে পারবেন।",
    starts_on: "2026-11-20",
    ends_on: "2026-11-21",
    registration_deadline: "2026-11-18",
    intro_time: "সকাল ৯টা – বিকাল ৫টা",
    venue: "স্কুল মাঠ ও বিজ্ঞানাগার",
    city: "কালাই সদর, জয়পুরহাট",
    chief_guest: "",
    fee: 0,
    contact_email: "okgs2003@gmail.com",
    contact_phone: "01711857205",
    accent: "#7c3aed",
    accent_2: "#06b6d4",
    logo_url: media("event-science-fair"),
    cover_image_url: media("campus-sciencefair"),
    poster_url: "",
    gallery_urls: [media("gallery-science-1"), media("gallery-science-2"), media("gallery-science-3"), media("gallery-science-4")].join("\n"),
    results_note: "",
    is_featured: 1,
    sort_order: 1,
    is_active: 1,
  },
];

const fairCategories = [
  { id: "faircat-model", fair_slug: "science-fair-2026", name: "বিজ্ঞান মডেল ও প্রজেক্ট", code: "MODEL", kind: "প্রজেক্ট", description: "হাতে তৈরি মডেল দিয়ে কোনো বৈজ্ঞানিক ধারণা বা সমাধান দেখানো।", rules: "দলপিছু ১টি মডেল\n৫ মিনিট উপস্থাপনা + ৩ মিনিট প্রশ্ন\nসম্পূর্ণ কাজ শিক্ষার্থীর নিজের হতে হবে", classes: "তৃতীয় – দশম শ্রেণি", team_size: 2, fee: 0, icon: "Atom", color: "#7c3aed", sort_order: 1, is_active: 1 },
  { id: "faircat-experiment", fair_slug: "science-fair-2026", name: "পরীক্ষা-নিরীক্ষা ডেমো", code: "EXP", kind: "পরীক্ষা", description: "মঞ্চে বা বুথে জীবন্ত পরীক্ষা দেখানো — নিরাপত্তা মানে মেনে।", rules: "নিরাপত্তা উপকরণ ব্যবহার বাধ্যতামূলক\nরাসায়নিক পদার্থ কেবল শিক্ষকের তত্ত্বাবধানে", classes: "ষষ্ঠ – দশম শ্রেণি", team_size: 2, fee: 0, icon: "FlaskConical", color: "#0ea5e9", sort_order: 2, is_active: 1 },
  { id: "faircat-robotics", fair_slug: "science-fair-2026", name: "রোবোটিক্স ও অটোমেশন", code: "ROBO", kind: "রোবোটিক্স", description: "সেন্সর-ভিত্তিক রোবট, স্মার্ট ডিভাইস ও স্বয়ংক্রিয় সমাধান।", rules: "আরডুইনো/মাইক্রোকন্ট্রোলার ব্যবহার করা যাবে\nবোর্ড ও তার ক্লাবে দেওয়া হবে", classes: "ষষ্ঠ – দশম শ্রেণি", team_size: 3, fee: 0, icon: "Cpu", color: "#f97316", sort_order: 3, is_active: 1 },
  { id: "faircat-code", fair_slug: "science-fair-2026", name: "প্রোগ্রামিং ও ওয়েব", code: "CODE", kind: "প্রোগ্রামিং", description: "ওয়েব অ্যাপ, ছোট গেম বা অ্যালগরিদম সমস্যার সমাধান।", rules: "ল্যাপটপ নিজে আনতে হবে\nলাইভ ডেমো ৫ মিনিট", classes: "পঞ্চম – দশম শ্রেণি", team_size: 2, fee: 0, icon: "Code2", color: "#2563eb", sort_order: 4, is_active: 1 },
  { id: "faircat-quiz", fair_slug: "science-fair-2026", name: "বিজ্ঞান কুইজ", code: "QUIZ", kind: "কুইজ", description: "স্কুল, উপজেলা ও আন্তঃস্কুল পর্যায়ের দ্রুতগতির বিজ্ঞান কুইজ।", rules: "৩ রাউন্ড: লিখিত, সরাসরি, বাজার দর\nদলপিছু ৩ জন", classes: "চতুর্থ – দশম শ্রেণি", team_size: 3, fee: 0, icon: "Brain", color: "#eab308", sort_order: 5, is_active: 1 },
  { id: "faircat-debate", fair_slug: "science-fair-2026", name: "বিজ্ঞান বিতর্ক", code: "DEBATE", kind: "বিতর্ক", description: "প্রযুক্তি ও বিজ্ঞান-সংক্রান্ত প্রস্তাব নিয়ে সংসদীয় ধাঁচের বিতর্ক।", rules: "দলপিছু ৩ জন বক্তা\nপ্রস্তাব মেলার দিন ঘোষণা করা হবে", classes: "সপ্তম – দশম শ্রেণি", team_size: 3, fee: 0, icon: "MessagesSquare", color: "#7c3aed", sort_order: 6, is_active: 1 },
  { id: "faircat-art", fair_slug: "science-fair-2026", name: "বিজ্ঞান পোস্টার ও চিত্রকর্ম", code: "ART", kind: "চিত্রকর্ম", description: "বিজ্ঞান-বিষয়ক পোস্টার, ইনফোগ্রাফিক ও চিত্রকর্ম প্রদর্শনী।", rules: "A2 বা A3 সাইজে আঁকতে হবে\nপরিষ্কার বাংলা/ইংরেজি লেবেল থাকবে", classes: "প্লে – দশম শ্রেণি", team_size: 1, fee: 0, icon: "Palette", color: "#ec4899", sort_order: 7, is_active: 1 },
  { id: "faircat-idea", fair_slug: "science-fair-2026", name: "বিগ আইডিয়া পিচ", code: "PITCH", kind: "অন্যান্য", description: "গ্রাম-বাংলার সমস্যার প্রযুক্তিনির্ভর সমাধান ৩ মিনিটে উপস্থাপন।", rules: "৩ মিনিট পিচ + ২ মিনিট প্রশ্ন\nস্লাইড ঐচ্ছিক", classes: "অষ্টম – দশম শ্রেণি", team_size: 2, fee: 0, icon: "Lightbulb", color: "#22c55e", sort_order: 8, is_active: 1 },
];

const fairSchedule = [
  { id: "fairslot-1", fair_slug: "science-fair-2026", title: "উদ্বোধনী অনুষ্ঠান", description: "দেশাত্মবোধক সংগীত, স্বাগত বক্তব্য ও ফিতা কেটে মেলার উদ্বোধন।", starts_at: "2026-11-20 09:00", ends_at: "2026-11-20 10:00", venue: "স্কুল মিলনায়তন", host: "অধ্যক্ষ", kind: "উদ্বোধন", sort_order: 1, is_active: 1 },
  { id: "fairslot-2", fair_slug: "science-fair-2026", title: "প্রকল্প প্রদর্শনী ও বিচার", description: "সব বুথ খোলা — বিচারকমণ্ডলী ক্যাটাগরি অনুযায়ী স্কোর করবেন।", starts_at: "2026-11-20 10:00", ends_at: "2026-11-20 13:00", venue: "স্কুল মাঠ", host: "বিচারকমণ্ডলী", kind: "প্রদর্শনী", sort_order: 2, is_active: 1 },
  { id: "fairslot-3", fair_slug: "science-fair-2026", title: "বিজ্ঞান কুইজ — লিখিত রাউন্ড", description: "সব দলের জন্য ৩০ মিনিটের লিখিত বাছাই পরীক্ষা।", starts_at: "2026-11-20 11:30", ends_at: "2026-11-20 12:15", venue: "শ্রেণিকক্ষ ১–৪", host: "কুইজ সেল", kind: "প্রতিযোগিতা", sort_order: 3, is_active: 1 },
  { id: "fairslot-4", fair_slug: "science-fair-2026", title: "রোবোটিক্স ডেমো অ্যাড্রিন", description: "রোবোটিক্স বুথে লাইভ ডেমো ও দর্শনার্থীদের জন্য হাতেকলমে সেশন।", starts_at: "2026-11-20 14:00", ends_at: "2026-11-20 15:30", venue: "কম্পিউটার ল্যাব", host: "কম্পিউটার ক্লাব", kind: "প্রদর্শনী", sort_order: 4, is_active: 1 },
  { id: "fairslot-5", fair_slug: "science-fair-2026", title: "বিজ্ঞান সেমিনার", description: "আমন্ত্রিত অতিথির আলোচনা: ‘প্রযুক্তি আর গ্রামীণ স্বপ্ন’।", starts_at: "2026-11-20 16:00", ends_at: "2026-11-20 17:00", venue: "মিলনায়তন", host: "ম্যাথ এন্ড সাইন্স ক্লাব", kind: "সেমিনার", sort_order: 5, is_active: 1 },
  { id: "fairslot-6", fair_slug: "science-fair-2026", title: "বিজ্ঞান বিতর্ক", description: "সেমিফাইনাল ও ফাইনাল — সংসদীয় ধাঁচে বিতর্ক।", starts_at: "2026-11-21 09:30", ends_at: "2026-11-21 11:30", venue: "মিলনায়তন", host: "ART Debating Society", kind: "প্রতিযোগিতা", sort_order: 6, is_active: 1 },
  { id: "fairslot-7", fair_slug: "science-fair-2026", title: "বিগ আইডিয়া পিচ", description: "শীর্ষ ৮টি দল ৩ মিনিটে নিজেদের ধারণা উপস্থাপন করবে।", starts_at: "2026-11-21 12:00", ends_at: "2026-11-21 13:30", venue: "মিলনায়তন", host: "আয়োজক কমিটি", kind: "প্রতিযোগিতা", sort_order: 7, is_active: 1 },
  { id: "fairslot-8", fair_slug: "science-fair-2026", title: "সাংস্কৃতিক পরিবেশনা", description: "ক্লাবের সাংস্কৃতিক দলের পরিবেশনা ও পথনাটক।", starts_at: "2026-11-21 14:30", ends_at: "2026-11-21 15:30", venue: "স্কুল মাঠ", host: "সাংস্কৃতিক দল", kind: "সাংস্কৃতিক", sort_order: 8, is_active: 1 },
  { id: "fairslot-9", fair_slug: "science-fair-2026", title: "পুরস্কার বিতরণ ও সমাপনী", description: "ক্যাটাগরিভিত্তিক বিজয়ীদের পুরস্কার, সনদ ও ক্রেস্ট প্রদান।", starts_at: "2026-11-21 16:00", ends_at: "2026-11-21 17:00", venue: "মিলনায়তন", host: "অধ্যক্ষ", kind: "পুরস্কার", sort_order: 9, is_active: 1 },
];

const fairCollections = [
  {
    id: "faircol-demo-1",
    fair_slug: "science-fair-2026",
    title: "নমুনা সংগ্রহ — সৌরবিদ্যুৎ মডেল",
    category: "বিজ্ঞান মডেল ও প্রজেক্ট",
    description: "এটি একটি নমুনা এন্ট্রি; অ্যাডমিন স্টুডিও থেকে সম্পাদনা করে আসল প্রকল্পের তথ্য বসান।",
    project_type: "মডেল",
    status: "প্রদর্শিত",
    position: "",
    score: 0,
    student_name: "নমুনা শিক্ষার্থী",
    student_id: "",
    class_level: "অষ্টম শ্রেণি",
    section: "ক",
    team_members: "দলনেতা ও সহযোগী সদস্যদের নাম এখানে লিখুন",
    club_slug: "alssm",
    image_url: media("gallery-science-4"),
    gallery_urls: "",
    video_url: "",
    certificate_url: "",
    note: "নমুনা এন্ট্রি — মুছে ফেলতে বা সম্পাদনা করতে পারবেন।",
    is_featured: 1,
    sort_order: 1,
    is_active: 1,
  },
  {
    id: "faircol-demo-2",
    fair_slug: "science-fair-2026",
    title: "নমুনা সংগ্রহ — ক্লাসরুম হেল্পার বট",
    category: "রোবোটিক্স ও অটোমেশন",
    description: "আরডুইনো ও আলট্রাসনিক সেন্সর দিয়ে বানানো একটি নমুনা রোবোটিক্স প্রকল্প।",
    project_type: "রোবোটিক্স",
    status: "চূড়ান্ত",
    position: "",
    score: 0,
    student_name: "নমুনা শিক্ষার্থী",
    student_id: "",
    class_level: "দশম শ্রেণি",
    section: "খ",
    team_members: "",
    club_slug: "alpcg",
    image_url: media("gallery-computer-2"),
    gallery_urls: "",
    video_url: "",
    certificate_url: "",
    note: "নমুনা এন্ট্রি।",
    is_featured: 0,
    sort_order: 2,
    is_active: 1,
  },
];

const themes = [
  {
    id: "theme-campus",
    name: "Campus Green",
    key: "campus-green",
    description: "স্কুলের মূল সবুজ-সোনালি পরিচয় — হোম ও ক্লাব পাতার ডিফল্ট থিম।",
    mode: "light",
    accent: "#15803d",
    accent_2: "#d97706",
    surface: "#ffffff",
    ink: "#0f2e21",
    hero_style: "glass",
    font_pair: "hind-noto",
    radius: 18,
    custom_css: "",
    custom_head: "",
    preview_image_url: "",
    is_default: 1,
    is_active: 1,
  },
  {
    id: "theme-neon",
    name: "Science Fair Neon",
    key: "fair-neon",
    description: "বিজ্ঞান মেলার জন্য নিয়ন-ভায়োলেট ও সায়ান — ডার্ক মোড, বড় টাইপোগ্রাফি।",
    mode: "dark",
    accent: "#8b5cf6",
    accent_2: "#22d3ee",
    surface: "#0b1020",
    ink: "#e2e8ff",
    hero_style: "gradient",
    font_pair: "hind",
    radius: 22,
    custom_css: "",
    custom_head: "",
    preview_image_url: "",
    is_default: 0,
    is_active: 1,
  },
  {
    id: "theme-lab",
    name: "Midnight Lab",
    key: "midnight-lab",
    description: "গাঢ় নীল ল্যাব-মুড, নিয়ন সবুজ অ্যাকসেন্ট — আইসিটি ও রোবোটিক্স পাতার জন্য।",
    mode: "dark",
    accent: "#22c55e",
    accent_2: "#38bdf8",
    surface: "#071a26",
    ink: "#dff6ef",
    hero_style: "full",
    font_pair: "hind",
    radius: 16,
    custom_css: "",
    custom_head: "",
    preview_image_url: "",
    is_default: 0,
    is_active: 1,
  },
  {
    id: "theme-paper",
    name: "Warm Paper",
    key: "warm-paper",
    description: "কাগজের মতো উষ্ণ ব্যাকগ্রাউন্ড, সেরিফ বাংলা টাইপ — সাহিত্য ও বিতর্কের জন্য।",
    mode: "light",
    accent: "#b45309",
    accent_2: "#0f766e",
    surface: "#fdf8ef",
    ink: "#3a2b12",
    hero_style: "minimal",
    font_pair: "noto",
    radius: 12,
    custom_css: "",
    custom_head: "",
    preview_image_url: "",
    is_default: 0,
    is_active: 1,
  },
  {
    id: "theme-festive",
    name: "Fair Day",
    key: "fair-day",
    description: "উৎসবের কমলা-গোলাপি, উজ্জ্বল কার্ড ও গোলাকার কোণ — ইভেন্ট ডে থিম।",
    mode: "light",
    accent: "#ea580c",
    accent_2: "#db2777",
    surface: "#fff7f2",
    ink: "#3b1104",
    hero_style: "gradient",
    font_pair: "baloo",
    radius: 26,
    custom_css: "",
    custom_head: "",
    preview_image_url: "",
    is_default: 0,
    is_active: 1,
  },
];

const slides = [
  {
    id: "slide-fair-2026",
    club_slug: "alssm",
    eyebrow: "২০ – ২১ নভেম্বর ২০২৬",
    title: "OKGS Science Fair 2026",
    description: "আবিষ্কারের উৎসবে সবার আমন্ত্রণ — মডেল, রোবোটিক্স, কুইজ, বিতর্ক আর বিগ আইডিয়া পিচ।",
    cta_label: "মেলা দেখুন",
    cta_href: "/fair/science-fair-2026",
    image_url: media("campus-sciencefair"),
    accent: "#7c3aed",
    sort_order: 1,
    is_active: 1,
  },
  {
    id: "slide-clubs",
    club_slug: "",
    eyebrow: "৫টি ক্লাব · এক ক্যাম্পাস",
    title: "ক্লাবেই গড়ে ওঠে আত্মবিশ্বাস",
    description: "বিজ্ঞান, ভাষা, কম্পিউটার, খেলাধুলা আর বিতর্ক — প্রতিটি ক্লাবের নিজস্ব সাইট, কমিটি ও গ্যালারি।",
    cta_label: "ক্লাবসমূহ",
    cta_href: "/clubs",
    image_url: media("hero-clubs"),
    accent: "#e7c27e",
    sort_order: 2,
    is_active: 1,
  },
  {
    id: "slide-campus",
    club_slug: "",
    eyebrow: "২০০৩ সাল থেকে",
    title: "কালাইয়ের প্রাণবন্ত ক্যাম্পাস",
    description: "প্লে থেকে দশম শ্রেণি — আবাসিক ও অনাবাসিক, নিজস্ব ল্যাব, পাঠাগার ও স্কুল বাস।",
    cta_label: "আমাদের সম্পর্কে",
    cta_href: "/#about",
    image_url: media("hero-campus"),
    accent: "#d1fae5",
    sort_order: 3,
    is_active: 1,
  },
  {
    id: "slide-language",
    club_slug: "aypg",
    eyebrow: "ল্যাংগুয়েজ ক্লাব",
    title: "শুদ্ধ ভাষা, সাবলীল উপস্থাপন",
    description: "আবৃত্তি, উপস্থিত বক্তৃতা, বিতর্ক আর বইপড়া — প্রতি সপ্তাহে নিয়মিত আসর।",
    cta_label: "ক্লাব দেখুন",
    cta_href: "/clubs/aypg",
    image_url: media("hero-clubs"),
    accent: "#0d9488",
    sort_order: 4,
    is_active: 1,
  },
  {
    id: "slide-computer",
    club_slug: "alpcg",
    eyebrow: "কম্পিউটার ক্লাব",
    title: "প্রোগ্রামিংয়ে হাতেখড়ি",
    description: "ওয়েব ডেভেলপমেন্ট, পাইথন সেশন আর আইসিটি প্রতিযোগিতা — সব ল্যাবেই।",
    cta_label: "ক্লাব দেখুন",
    cta_href: "/clubs/alpcg",
    image_url: media("hero-science"),
    accent: "#2563eb",
    sort_order: 5,
    is_active: 1,
  },
];

const notices = [
  {
    id: "notice-fair-reg",
    club_slug: "alssm",
    title: "OKGS Science Fair 2026 — নিবন্ধন শুরু",
    body:
      "২০ ও ২১ নভেম্বর অনুষ্ঠিতব্য বিজ্ঞান মেলায় নিবন্ধন শুরু হয়েছে। নিবন্ধনের শেষ তারিখ ১৮ নভেম্বর ২০২৬। ক্লাস-সাপেক্ষে ক্যাটাগরি ও নিয়মাবলি মেলার পাতায় দেখা যাবে।",
    type: "কার্যক্রম",
    published_at: "2026-10-01 09:00",
    is_active: 1,
  },
  {
    id: "notice-club-sites",
    club_slug: "",
    title: "প্রতিটি ক্লাবের নিজস্ব ওয়েবসাইট চালু",
    body: "এখন থেকে পাঁচটি ক্লাবের আলাদা সাইট ও অ্যাডমিন প্যানেল চালু হয়েছে — ক্লাবের নিজস্ব সাবডোমেইন থেকে অ্যাডমিন লগইন করে ছবি আপলোড করা যাবে।",
    type: "সাধারণ",
    published_at: "2026-09-28 10:00",
    is_active: 1,
  },
  {
    id: "notice-student-login",
    club_slug: "",
    title: "শিক্ষার্থী ও শিক্ষক লগইন চালু",
    body: "স্কুল আইডি নম্বর অথবা ইমেইল দিয়ে /sf/login-এ লগইন করে পাওনা, ফান্ড জমা ও মেলার QR পাস দেখা যাবে।",
    type: "জরুরি",
    published_at: "2026-09-27 12:00",
    is_active: 1,
  },
];

const banners = [
  {
    id: "banner-fair-2026",
    label: "২০–২১ নভেম্বর ২০২৬",
    title: "OKGS Science Fair 2026",
    description: "নিবন্ধন চলছে — মডেল, রোবোটিক্স, কুইজ, বিতর্ক, পোস্টার ও বিগ আইডিয়া পিচ।",
    cta_label: "নিবন্ধন করুন",
    cta_href: "/fair/science-fair-2026#register",
    image_url: media("banner-clubs"),
    accent: "#7c3aed",
    sort_order: 1,
    is_active: 1,
  },
  {
    id: "banner-admission",
    label: "ভর্তি চলছে",
    title: "২০২৬ শিক্ষাবর্ষে ভর্তি",
    description: "প্লে থেকে দশম শ্রেণি — আবাসিক ও অনাবাসিক। সীমিত আসন, দ্রুত যোগাযোগ করুন।",
    cta_label: "ভর্তি তথ্য",
    cta_href: "/#admission",
    image_url: media("banner-admission"),
    accent: "#14532d",
    sort_order: 2,
    is_active: 1,
  },
];

const updates = [
  { id: "update-1", title: "বিজ্ঞান মেলার পোস্টার প্রকাশিত", description: "মেলার অফিসিয়াল পোস্টার ও ক্যাটাগরি তালিকা প্রকাশ করা হয়েছে।", date: "2026-10-02", kind: "বিজ্ঞান", is_active: 1 },
  { id: "update-2", title: "ক্লাব সাবসাইট চালু", description: "পাঁচটি ক্লাবের নিজস্ব সাইট ও অ্যাডমিন প্যানেল চালু হয়েছে।", date: "2026-09-30", kind: "ক্লাব", is_active: 1 },
  { id: "update-3", title: "শিক্ষার্থী QR পাস", description: "প্রতিটি শিক্ষার্থীর জন্য QR পাস তৈরি ও স্ক্যান-ভেরিফিকেশন সিস্টেম চালু।", date: "2026-09-29", kind: "কার্যক্রম", is_active: 1 },
];

const news = [
  {
    id: "news-fair-announce",
    slug: "science-fair-2026-announcement",
    title: "OKGS Science Fair 2026 — ২০ ও ২১ নভেম্বর",
    excerpt: "মডেল, রোবোটিক্স, কুইজ, বিতর্ক ও বিগ আইডিয়া পিচ — আটটি ক্যাটাগরিতে নিবন্ধন শুরু।",
    body:
      "স্কুলের বার্ষিক বিজ্ঞান মেলা এ বছর ২০ ও ২১ নভেম্বর অনুষ্ঠিত হবে। এ বছরের মূল আকর্ষণ — রোবোটিক্স ও অটোমেশন বুথ এবং ‘বিগ আইডিয়া পিচ’ পর্ব, যেখানে শিক্ষার্থীরা গ্রাম-বাংলার বাস্তব সমস্যার প্রযুক্তিনির্ভর সমাধান উপস্থাপন করবে।\n\nনিবন্ধন ফি নেই। প্রতিটি দলে সর্বোচ্চ তিনজন সদস্য থাকতে পারবে এবং প্রতিটি দলকে একটি বুথ বরাদ্দ করা হবে। বিচারকমণ্ডলী uniqueness, presentation ও scientific reasoning — এই তিন মানদণ্ডে স্কোর করবেন।\n\nশিক্ষার্থীরা তাদের আইডি নম্বর দিয়ে /sf/login-এ লগইন করে নিজেদের QR পাস ও ফান্ডের তথ্য দেখতে পারবে।",
    image_url: media("news-science-fair"),
    category: "বিজ্ঞান মেলা",
    author: "ওকেজিএস বার্তা",
    club_slug: "alssm",
    published_at: "2026-10-01 08:30",
    is_featured: 1,
    is_active: 1,
  },
  {
    id: "news-club-sites",
    slug: "club-websites-launched",
    title: "প্রতিটি ক্লাব পেল নিজস্ব ওয়েবসাইট",
    excerpt: "পাঁচটি ক্লাবের জন্য আলাদা সাইট, অ্যাডমিন লগইন, ক্লাউডিনারি আপলোড আর নিজস্ব সাবডোমেইন।",
    body:
      "ক্লাবের ছবি, কমিটি, আয়োজন আর অর্জন আলাদাভাবে দেখানোর জন্য প্রতিটি ক্লাবের জন্য আলাদা সাইট তৈরি করা হয়েছে। ক্লাবের অ্যাডমিন নিজে লগইন করে কভার ছবি, কমিটির সদস্যদের ছবি ও আয়োজনের তথ্য হালনাগাদ করতে পারবেন।\n\nপ্রতিটি সাইট নিজস্ব সাবডোমেইনে চলে — ALSSM, AYPG, ALPCG, AYGSM আর ART Debating Society। ছবি আপলোড হয় সরাসরি Cloudinary-তে, তাই সাইট দ্রুত থাকে।",
    image_url: media("news-clubs"),
    category: "ক্যাম্পাস",
    author: "ওকেজিএস বার্তা",
    club_slug: "",
    published_at: "2026-09-30 11:00",
    is_featured: 0,
    is_active: 1,
  },
  {
    id: "news-web-contest",
    slug: "web-development-contest-2026",
    title: "ওয়েব ডেভেলপমেন্ট কনটেস্ট ২০২৬",
    excerpt: "কম্পিউটার ক্লাবের আয়োজনে স্কুলের প্রথম ওয়েব ডেভেলপমেন্ট প্রতিযোগিতা।",
    body:
      "কম্পিউটার ক্লাবের আয়োজনে স্কুলের শিক্ষার্থীদের জন্য ওয়েব ডেভেলপমেন্ট প্রতিযোগিতা অনুষ্ঠিত হয়। শিক্ষার্থীরা HTML, CSS ও জাভাস্ক্রিপ্ট দিয়ে নিজেদের স্কুল, ক্লাব বা গ্রামের জন্য একটি পেজ বানিয়েছে।\n\nসেরা প্রকল্পগুলো স্কুলের ওয়েবসাইটে প্রদর্শন করা হবে এবং বিজয়ীরা মেলার দিন সনদ পাবে।",
    image_url: media("post-webcamp"),
    category: "শিক্ষা",
    author: "কম্পিউটার ক্লাব",
    club_slug: "alpcg",
    published_at: "2026-09-25 15:00",
    is_featured: 0,
    is_active: 1,
  },
];

const settings = [
  { id: "setting-logo", key: "logo_url", label: "প্রতিষ্ঠানের লোগো", field_kind: "image", value: media("school-logo"), description: "হেডার, ফুটার ও মেলার পাতায় দেখানো হবে।" },
  { id: "setting-school-logo-alt", key: "logo_url_alt", label: "লোগোর বিকল্প (সাদা ব্যাকগ্রাউন্ড)", field_kind: "image", value: "", description: "ডার্ক থিমে ব্যবহারের জন্য ঐচ্ছিক।" },
  { id: "setting-fair-logo", key: "fair_logo_url", label: "বিজ্ঞান মেলার লোগো", field_kind: "image", value: media("event-science-fair"), description: "হোমপেজের বড় মেলা-ব্যানারে দেখানো হবে।" },
  { id: "setting-about-image", key: "about_image_url", label: "পরিচিতি অংশের ছবি", field_kind: "image", value: media("about-school"), description: "‘আমাদের পরিচিতি’ ব্লকের ছবি।" },
  { id: "setting-admission-image", key: "admission_image_url", label: "ভর্তি অংশের ছবি", field_kind: "image", value: media("admission-desk"), description: "ভর্তি সেকশনের ছবি।" },
  { id: "setting-about-extra", key: "about_extra", label: "পরিচিতির অতিরিক্ত লেখা", field_kind: "textarea", value: "নিজস্ব পাঠাগার, আধুনিক কম্পিউটার ল্যাব, ছাত্র-ছাত্রীনিবাস, স্কুল বাস আর পাঁচটি সক্রিয় ক্লাব।", description: "পরিচিতি অংশের দ্বিতীয় অনুচ্ছেদ।" },
  { id: "setting-admission-note", key: "admission_note", label: "ভর্তি অংশের লেখা", field_kind: "textarea", value: "প্লে থেকে দশম শ্রেণি পর্যন্ত আবাসিক ও অনাবাসিক ভর্তি চলছে। প্রি-প্রাইমারিতে আবাকাস, স্পোকেন ইংলিশ, কম্পিউটার ও কুরআন শিক্ষায় বিশেষ গুরুত্ব দেওয়া হয়।", description: "ভর্তি সেকশনের মূল লেখা।" },
  { id: "setting-gallery-note", key: "gallery_note", label: "গ্যালারির টীকা", field_kind: "textarea", value: "বিজ্ঞান মেলা, ক্রীড়া প্রতিযোগিতা, বিতর্ক, আবৃত্তি আর আইসিটি কর্মশালার ছবি।", description: "গ্যালারির নিচে দেখানো হবে।" },
  { id: "setting-quote-text", key: "quote_text", label: "উদ্ধৃতি", value: "This is one of the best school in Bangladesh", description: "হোমপেজের উদ্ধৃতি অংশ।" },
  { id: "setting-quote-author", key: "quote_author", value: "— একজন অভিভাবক", description: "উদ্ধৃতির উৎস।" },
  { id: "setting-badge-year", key: "hero_badge_year", label: "হিরো ব্যাজ: সাল", value: "২০০৩", description: "স্লাইডারের ডান পাশের ব্যাজ।" },
  { id: "setting-badge-place", key: "hero_badge_place", label: "হিরো ব্যাজ: স্থান", value: "কালাই, জয়পুরহাট", description: "স্লাইডারের ব্যাজে দেখানো হবে।" },
  { id: "setting-site-name", key: "site_name", label: "প্রতিষ্ঠানের নাম", value: "ওমর কিন্ডারগার্টেন স্কুল এন্ড ওমর গার্টেন একাডেমি", description: "ওয়েবসাইটে প্রদর্শিত প্রতিষ্ঠানের নাম।" },
  { id: "setting-site-short", key: "short_name", label: "সংক্ষিপ্ত নাম", value: "OKGS", description: "মেনু, ফুটার ও লোগোতে ব্যবহৃত নাম।" },
  { id: "setting-tagline", key: "tagline", label: "সংক্ষিপ্ত পরিচিতি", value: "২০০৩ সাল থেকে কালাই, জয়পুরহাটে মানসম্মত শিক্ষা — প্লে থেকে দশম শ্রেণি।", description: "হেডার ও ফুটারে প্রদর্শিত পরিচিতি।" },
  { id: "setting-about", key: "about", label: "প্রতিষ্ঠান সম্পর্কে", value: "ওমর কিন্ডারগার্টেন স্কুল ও ওমর গার্টেন একাডেমি জয়পুরহাট জেলার কালাই উপজেলা সদরে অবস্থিত একটি স্বনামধন্য শিক্ষা প্রতিষ্ঠান। ২০০৩ সালের ১লা জানুয়ারি বিশিষ্ট শিক্ষানুরাগী আলহাজ্ব আব্দুর রশিদ তালুকদার প্রতিষ্ঠানটি প্রতিষ্ঠা করেন।", description: "হোমপেজের সংক্ষিপ্ত পরিচিতি।" },
  { id: "setting-mission", key: "mission", label: "লক্ষ্য", value: "মানসম্মত শিক্ষা, শৃঙ্খলা ও মানবিক মূল্যবোধে গড়ে তুলি আগামী প্রজন্ম।", description: "পরিচিতি অংশে প্রদর্শিত লক্ষ্য।" },
  { id: "setting-club-mission", key: "club_mission", label: "ক্লাব তথ্যকেন্দ্রের পরিচিতি", value: "স্কুলের পাঁচটি ক্লাবের আয়োজন, কমিটি, ছবি ও অর্জন — এক জায়গায়, আর প্রতিটি ক্লাবের নিজস্ব সাইট।", description: "/clubs পাতার ভূমিকা লেখা।" },
  { id: "setting-email", key: "email", label: "ইমেইল", value: "okgs2003@gmail.com", description: "প্রধান যোগাযোগ ইমেইল।" },
  { id: "setting-phone", key: "phone", label: "হেল্পলাইন", value: "01711857205", description: "প্রধান হেল্পলাইন নম্বর।" },
  { id: "setting-admission-phone", key: "admission_phone", label: "ভর্তি ও হোস্টেল নম্বর", value: "01329625700", description: "ভর্তি ও আবাসিক তথ্যের নম্বর।" },
  { id: "setting-secondary-phone", key: "phone_secondary", label: "অফিস নম্বর", value: "05725-56351-52", description: "অতিরিক্ত অফিস যোগাযোগ নম্বর।" },
  { id: "setting-address", key: "address", label: "ঠিকানা", value: "স্কুল কলেজ পাড়া, কালাই সদর, জয়পুরহাট", description: "ফুটারে প্রদর্শিত ঠিকানা।" },
  { id: "setting-hours", key: "office_hours", label: "অফিস সময়", value: "রবি – বৃহস্পতি, সকাল ৮টা – দুপুর ২টা", description: "যোগাযোগ পাতার অফিস সময়।" },
  { id: "setting-facebook", key: "facebook_url", label: "ফেসবুক পেজ", value: "https://www.facebook.com/omarkgschool/", description: "ফুটার ও যোগাযোগে দেখানো হবে।" },
  { id: "setting-youtube", key: "youtube_url", label: "ইউটিউব চ্যানেল", value: "https://www.youtube.com/channel/UCE-VL9Ap-kLeKuvM1D3mmYA", description: "ফুটার ও যোগাযোগে দেখানো হবে।" },
  { id: "setting-founders", key: "founder", label: "প্রতিষ্ঠাতা", value: "আলহাজ্ব আব্দুর রশিদ তালুকদার — প্রতিষ্ঠা: ১লা জানুয়ারি ২০০৩", description: "পরিচিতি অংশে দেখানো হবে।" },
  { id: "setting-principal", key: "principal", label: "অধ্যক্ষ", value: "ওমর আব্দুল আজিজ তালুকদার", description: "শিক্ষক পরিচিতি অংশে দেখানো হবে।" },
  { id: "setting-fair-mode", key: "fair_mode", label: "সাইট মোড", field_kind: "text", value: "school", description: "‘school’ = পুরো স্কুল সাইট, ‘fair’ = পুরো সাইট বিজ্ঞান মেলার সাইট হয়ে যাবে।" },
  { id: "setting-fair-mode-slug", key: "fair_mode_slug", label: "সক্রিয় মেলা", field_kind: "text", value: "science-fair-2026", description: "কোন মেলাটিকে হোমপেজে দেখানো হবে।" },
  { id: "setting-fair-banner", key: "fair_banner_enabled", label: "হোমপেজে বড় মেলা-ব্যানার", field_kind: "text", value: "1", description: "‘0’ করলে হোমপেজের ultra big ব্যানার লুকিয়ে যাবে।" },
  { id: "setting-fair-kicker", key: "fair_banner_kicker", label: "ব্যানার লেবেল", value: "২০ – ২১ নভেম্বর ২০২৬ · স্কুল মাঠ", description: "বড় ব্যানারের উপরের ছোট লেখা।" },
  { id: "setting-fair-headline", key: "fair_banner_title", label: "ব্যানার শিরোনাম", value: "OKGS Science Fair 2026", description: "হোমপেজের সবচেয়ে বড় লেখা।" },
  { id: "setting-fair-sub", key: "fair_banner_subtitle", label: "ব্যানারের উপশিরোনাম", field_kind: "textarea", value: "আবিষ্কারের উৎসবে সবার আমন্ত্রণ — মডেল, রোবোটিক্স, কুইজ, বিতর্ক ও বিগ আইডিয়া পিচ।", description: "ব্যানারের নিচের লেখা।" },
  { id: "setting-fair-reg-open", key: "fair_registration_open", label: "নিবন্ধন চালু", field_kind: "text", value: "1", description: "‘0’ করলে নিবন্ধন বন্ধ দেখাবে।" },
  { id: "setting-portal-note", key: "portal_note", label: "লগইন পাতার নির্দেশনা", field_kind: "textarea", value: "স্কুল আইডি নম্বর অথবা ইমেইল দিয়ে লগইন করুন। আইডি বা পাসওয়ার্ড না জানা থাকলে ক্লাস টিচারের কাছে যোগাযোগ করুন।", description: "/sf/login পাতায় দেখানো হবে।" },
  { id: "setting-footer-note", key: "footer_note", label: "ফুটারের নোট", field_kind: "textarea", value: "সব ক্লাবের তথ্য এক জায়গায় — এবং প্রতিটি ক্লাবের নিজস্ব সাইট। পাঁচটি ক্লাব: ALSSM, AYPG, ALPCG, AYGSM ও ART Debating Society।", description: "ফুটারে ছোট করে দেখানো হবে।" },
];


const teachers = [
  { id: "teacher-principal", name: "ওমর আব্দুল আজিজ তালুকদার", role: "অধ্যক্ষ", subject: "প্রশাসন ও বিজ্ঞান", kind: "teacher", qualification: "", bio: "প্রতিষ্ঠানের অধ্যক্ষ এবং সব ক্লাব কার্যক্রমের প্রধান পৃষ্ঠপোষক।", photo_url: media("teacher-principal"), sort_order: 1, is_active: 1 },
  { id: "teacher-rahomotullah", name: "মোঃ রহমতুল্লাহ পিকে", role: "সহকারী প্রধান শিক্ষক", subject: "পদার্থবিজ্ঞান", kind: "teacher", qualification: "", bio: "ম্যাথ এন্ড সাইন্স ক্লাবের (ALSSM) উপদেষ্টা শিক্ষক।", photo_url: media("teacher-physics"), sort_order: 2, is_active: 1 },
  { id: "teacher-meherul", name: "মোঃ মেহেরুল ইসলাম", role: "সহকারী শিক্ষক (আইসিটি)", subject: "কম্পিউটার ও আইসিটি", kind: "teacher", qualification: "", bio: "কম্পিউটার ক্লাবের (ALPCG) উপদেষ্টা — ল্যাব ও ওয়েব প্রকল্পের তত্ত্বাবধায়ক।", photo_url: media("teacher-ict"), sort_order: 3, is_active: 1 },
  { id: "teacher-fatema", name: "মোছাঃ ফাতেমা আক্তার", role: "সহকারী শিক্ষিকা", subject: "বাংলা", kind: "female-teacher", qualification: "", bio: "ল্যাংগুয়েজ ক্লাবের (AYPG) উপদেষ্টা — আবৃত্তি ও রচনার প্রশিক্ষণ দেন।", photo_url: media("teacher-bangla"), sort_order: 4, is_active: 1 },
  { id: "teacher-kalam", name: "মোঃ আবুল কালাম আজাদ", role: "শারীরিক শিক্ষক", subject: "শরীরচর্চা", kind: "teacher", qualification: "", bio: "স্পোর্টিং ক্লাবের (AYGSM) উপদেষ্টা — স্কুল দলের প্রশিক্ষণ পরিচালনা করেন।", photo_url: media("staff-office"), sort_order: 5, is_active: 1 },
  { id: "teacher-rozina", name: "মোছাঃ রোজিনা আক্তার", role: "সহকারী শিক্ষিকা", subject: "সংগীত ও সাংস্কৃতিক", kind: "female-teacher", qualification: "", bio: "ART Debating Society-র উপদেষ্টা — বিতর্ক ও সাংস্কৃতিক আয়োজন পরিচালনা করেন।", photo_url: media("teacher-nursery"), sort_order: 6, is_active: 1 },
];

const clubMembers = [
  { id: "mem-alssm-1", club_slug: "alssm", name: "মোঃ রহমতুল্লাহ পিকে", role: "উপদেষ্টা", class_room: "সহকারী প্রধান শিক্ষক", section: "", member_no: "", session_year: "২০২৬", photo_url: media("teacher-physics"), bio: "পদার্থবিজ্ঞানের শিক্ষক; শিক্ষার্থীদের সঙ্গে নিয়ে নিজের হাতে মডেল বানান।", achievement: "", phone: "", email: "", facebook_url: "", sort_order: 1, is_active: 1 },
  { id: "mem-alssm-2", club_slug: "alssm", name: "সভাপতির নাম বসান", role: "সভাপতি", class_room: "শ্রেণি লিখুন", section: "", member_no: "", session_year: "২০২৬", photo_url: "", bio: "অ্যাডমিন স্টুডিও থেকে নাম, ছবি ও পরিচিতি বসান।", achievement: "", phone: "", email: "", facebook_url: "", sort_order: 2, is_active: 1 },
  { id: "mem-alssm-3", club_slug: "alssm", name: "সাধারণ সম্পাদকের নাম বসান", role: "সাধারণ সম্পাদক", class_room: "শ্রেণি লিখুন", section: "", member_no: "", session_year: "২০২৬", photo_url: "", bio: "মেলার সমন্বয়কের দায়িত্বে থাকেন।", achievement: "", phone: "", email: "", facebook_url: "", sort_order: 3, is_active: 1 },
  { id: "mem-alssm-4", club_slug: "alssm", name: "যুগ্ম সম্পাদকের নাম বসান", role: "যুগ্ম সম্পাদক", class_room: "শ্রেণি লিখুন", section: "", member_no: "", session_year: "২০২৬", photo_url: "", bio: "", achievement: "", phone: "", email: "", facebook_url: "", sort_order: 4, is_active: 1 },
  { id: "mem-alssm-5", club_slug: "alssm", name: "তহবিল সম্পাদকের নাম বসান", role: "তহবিল সম্পাদক", class_room: "শ্রেণি লিখুন", section: "", member_no: "", session_year: "২০২৬", photo_url: "", bio: "মেলার ফান্ড ও খরচের হিসাব রাখেন।", achievement: "", phone: "", email: "", facebook_url: "", sort_order: 5, is_active: 1 },
  { id: "mem-aypg-1", club_slug: "aypg", name: "মোছাঃ ফাতেমা আক্তার", role: "উপদেষ্টা", class_room: "সহকারী শিক্ষিকা", section: "", member_no: "", session_year: "২০২৬", photo_url: media("teacher-bangla"), bio: "বাংলা ভাষা ও সাহিত্যের শিক্ষিকা; আবৃত্তি প্রশিক্ষণ দেন।", achievement: "", phone: "", email: "", facebook_url: "", sort_order: 1, is_active: 1 },
  { id: "mem-aypg-2", club_slug: "aypg", name: "সভাপতির নাম বসান", role: "সভাপতি", class_room: "শ্রেণি লিখুন", section: "", member_no: "", session_year: "২০২৬", photo_url: "", bio: "অ্যাডমিন স্টুডিও থেকে তথ্য যোগ করুন।", achievement: "", phone: "", email: "", facebook_url: "", sort_order: 2, is_active: 1 },
  { id: "mem-aypg-3", club_slug: "aypg", name: "সাধারণ সম্পাদকের নাম বসান", role: "সাধারণ সম্পাদক", class_room: "শ্রেণি লিখুন", section: "", member_no: "", session_year: "২০২৬", photo_url: "", bio: "", achievement: "", phone: "", email: "", facebook_url: "", sort_order: 3, is_active: 1 },
  { id: "mem-alpcg-1", club_slug: "alpcg", name: "মোঃ মেহেরুল ইসলাম", role: "উপদেষ্টা", class_room: "সহকারী শিক্ষক (আইসিটি)", section: "", member_no: "", session_year: "২০২৬", photo_url: media("teacher-ict"), bio: "কম্পিউটার ল্যাব পরিচালনা ও ওয়েব প্রকল্পের তত্ত্বাবধান করেন।", achievement: "", phone: "", email: "", facebook_url: "", sort_order: 1, is_active: 1 },
  { id: "mem-alpcg-2", club_slug: "alpcg", name: "সভাপতির নাম বসান", role: "সভাপতি", class_room: "শ্রেণি লিখুন", section: "", member_no: "", session_year: "২০২৬", photo_url: "", bio: "", achievement: "", phone: "", email: "", facebook_url: "", sort_order: 2, is_active: 1 },
  { id: "mem-alpcg-3", club_slug: "alpcg", name: "সাধারণ সম্পাদকের নাম বসান", role: "সাধারণ সম্পাদক", class_room: "শ্রেণি লিখুন", section: "", member_no: "", session_year: "২০২৬", photo_url: "", bio: "", achievement: "", phone: "", email: "", facebook_url: "", sort_order: 3, is_active: 1 },
  { id: "mem-aygsm-1", club_slug: "aygsm", name: "মোঃ আবুল কালাম আজাদ", role: "উপদেষ্টা", class_room: "শারীরিক শিক্ষক", section: "", member_no: "", session_year: "২০২৬", photo_url: media("staff-office"), bio: "স্কুল দলের প্রশিক্ষণ ও ক্রীড়া আয়োজন পরিচালনা করেন।", achievement: "", phone: "", email: "", facebook_url: "", sort_order: 1, is_active: 1 },
  { id: "mem-aygsm-2", club_slug: "aygsm", name: "সভাপতির নাম বসান", role: "সভাপতি", class_room: "শ্রেণি লিখুন", section: "", member_no: "", session_year: "২০২৬", photo_url: "", bio: "", achievement: "", phone: "", email: "", facebook_url: "", sort_order: 2, is_active: 1 },
  { id: "mem-aygsm-3", club_slug: "aygsm", name: "সাধারণ সম্পাদকের নাম বসান", role: "সাধারণ সম্পাদক", class_room: "শ্রেণি লিখুন", section: "", member_no: "", session_year: "২০২৬", photo_url: "", bio: "", achievement: "", phone: "", email: "", facebook_url: "", sort_order: 3, is_active: 1 },
  { id: "mem-artds-1", club_slug: "artds", name: "মোছাঃ রোজিনা আক্তার", role: "উপদেষ্টা", class_room: "সহকারী শিক্ষিকা", section: "", member_no: "", session_year: "২০২৬", photo_url: media("teacher-nursery"), bio: "বিতর্ক ও সাংস্কৃতিক আয়োজনের তত্ত্বাবধায়ক।", achievement: "", phone: "", email: "", facebook_url: "", sort_order: 1, is_active: 1 },
  { id: "mem-artds-2", club_slug: "artds", name: "সভাপতির নাম বসান", role: "সভাপতি", class_room: "শ্রেণি লিখুন", section: "", member_no: "", session_year: "২০২৬", photo_url: "", bio: "", achievement: "", phone: "", email: "", facebook_url: "", sort_order: 2, is_active: 1 },
  { id: "mem-artds-3", club_slug: "artds", name: "সাধারণ সম্পাদকের নাম বসান", role: "সাধারণ সম্পাদক", class_room: "শ্রেণি লিখুন", section: "", member_no: "", session_year: "২০২৬", photo_url: "", bio: "", achievement: "", phone: "", email: "", facebook_url: "", sort_order: 3, is_active: 1 },
];

const clubEvents = [
  { id: "event-fair-2026", club_slug: "alssm", title: "OKGS Science Fair 2026", description: "প্রতিষ্ঠানের সবচেয়ে বড় আয়োজন — আটটি ক্যাটাগরিতে প্রতিযোগিতা, প্রদর্শনী ও সেমিনার।", event_date: "2026-11-20", event_time: "সকাল ৯টা", venue: "স্কুল মাঠ ও বিজ্ঞানাগার", event_type: "প্রদর্শনী", registration_deadline: "2026-11-18", registration_link: "/fair/science-fair-2026#register", image_url: media("event-science-fair"), is_featured: 1, sort_order: 1, is_active: 1 },
  { id: "event-alssm-meet", club_slug: "alssm", title: "সাপ্তাহিক বিজ্ঞান আড্ডা", description: "প্রতি বৃহস্পতিবার ছোট পরীক্ষা, ধাঁধা ও অলিম্পিয়াড প্রস্তুতি।", event_date: "2026-11-05", event_time: "বিকাল ৪টা", venue: "বিজ্ঞানাগার", event_type: "সভা", is_featured: 0, sort_order: 2, is_active: 1 },
  { id: "event-aypg-asor", club_slug: "aypg", title: "মাসিক কবিতার আসর", description: "নিজের লেখা কবিতা পাঠ ও প্রিয় কবিতা আবৃত্তি।", event_date: "2026-11-12", event_time: "সকাল ৯টা", venue: "স্কুল পাঠাগার", event_type: "আয়োজন", is_featured: 0, sort_order: 1, is_active: 1 },
  { id: "event-alpcg-web", club_slug: "alpcg", title: "প্রথম ওয়েবসাইট কর্মশালা", description: "HTML ও CSS দিয়ে নিজের পরিচয়পাতা বানানো — শেষ দিনে সবার সামনে উপস্থাপন।", event_date: "2026-11-14", event_time: "বিকাল ৩টা", venue: "কম্পিউটার ল্যাব", event_type: "ওয়ার্কশপ", is_featured: 1, sort_order: 1, is_active: 1 },
  { id: "event-aygsm-sports", club_slug: "aygsm", title: "আন্তঃশ্রেণি ফুটবল", description: "শ্রেণিভিত্তিক দল নিয়ে ফুটবল লিগ — ফাইনাল মেলার সপ্তাহে।", event_date: "2026-11-19", event_time: "বিকাল ৪টা", venue: "স্কুল মাঠ", event_type: "প্রতিযোগিতা", is_featured: 0, sort_order: 1, is_active: 1 },
  { id: "event-artds-debate", club_slug: "artds", title: "আন্তঃশ্রেণি বিতর্ক প্রতিযোগিতা", description: "সংসদীয় ধাঁচে বিতর্ক — সেরা বক্তা ও সেরা দলকে পুরস্কার।", event_date: "2026-11-18", event_time: "বিকাল ৪টা", venue: "মিলনায়তন", event_type: "প্রতিযোগিতা", is_featured: 0, sort_order: 1, is_active: 1 },
];

const facilities = [
  { id: "facility-bus", title: "বাস সার্ভিস", description: "শিক্ষার্থীদের যাতায়াতের জন্য প্রতিষ্ঠানের নিজস্ব বাস।", icon: "Sparkles", image_url: "", sort_order: 1, is_active: 1 },
  { id: "facility-security", title: "শিক্ষার্থীর নিরাপত্তা", description: "সিসি ক্যামেরার সার্বক্ষণিক তত্ত্বাবধান ও ইভটিজিং প্রতিরোধ সেল।", icon: "ShieldCheck", image_url: "", sort_order: 2, is_active: 1 },
  { id: "facility-hostel", title: "আবাসিক ব্যবস্থা", description: "ছেলে ও মেয়েদের জন্য আলাদা দুটি কোলাহলমুক্ত আবাসিক ভবন।", icon: "Sparkles", image_url: "", sort_order: 3, is_active: 1 },
  { id: "facility-lab", title: "কম্পিউটার ল্যাব", description: "অত্যাধুনিক কম্পিউটার ল্যাব; সবার জন্য কম্পিউটার শিক্ষা বাধ্যতামূলক।", icon: "Monitor", image_url: "", sort_order: 4, is_active: 1 },
  { id: "facility-library", title: "সমৃদ্ধ পাঠাগার", description: "২০০০-এর অধিক বই সমৃদ্ধ নিজস্ব লাইব্রেরি (এবং পাঁচ ক্লাবের আসর)।", icon: "BookOpen", image_url: "", sort_order: 5, is_active: 1 },
  { id: "facility-canteen", title: "ক্যান্টিন", description: "স্কুল ক্যাম্পাসেই খাবারের জন্য নিজস্ব ক্যান্টিন।", icon: "Sparkles", image_url: "", sort_order: 6, is_active: 1 },
];

const stats = [
  { id: "stat-founded", label: "প্রতিষ্ঠা সাল", value: "২০০৩", note: "", icon: "Sparkles", sort_order: 1, is_active: 1 },
  { id: "stat-students", label: "শিক্ষার্থী", value: "১১০০+", note: "", icon: "Users", sort_order: 2, is_active: 1 },
  { id: "stat-staff", label: "শিক্ষক-কর্মচারী", value: "৮০", note: "", icon: "Users", sort_order: 3, is_active: 1 },
  { id: "stat-clubs", label: "সক্রিয় ক্লাব", value: "৫", note: "প্রত্যেকের নিজস্ব সাইট", icon: "Trophy", sort_order: 4, is_active: 1 },
];

export interface SeedPlan {
  resource: ResourceName;
  rows: Array<Record<string, string | number>>;
}

const asRows = (rows: Array<Record<string, unknown>>) => rows as unknown as Array<Record<string, string | number>>;

export const seeds: SeedPlan[] = [
  { resource: "clubs", rows: asRows(clubs) },
  { resource: "slides", rows: asRows(slides) },
  { resource: "notices", rows: asRows(notices) },
  { resource: "banners", rows: asRows(banners) },
  { resource: "news", rows: asRows(news) },
  { resource: "updates", rows: asRows(updates) },
  { resource: "fairs", rows: asRows(fairs) },
  { resource: "fair_categories", rows: asRows(fairCategories) },
  { resource: "fair_schedule", rows: asRows(fairSchedule) },
  { resource: "fair_collections", rows: asRows(fairCollections) },
  { resource: "themes", rows: asRows(themes) },
  { resource: "club_events", rows: asRows(clubEvents) },
  { resource: "club_members", rows: asRows(clubMembers) },
  { resource: "teachers", rows: asRows(teachers) },
  { resource: "facilities", rows: asRows(facilities) },
  { resource: "stats", rows: asRows(stats) },
  { resource: "settings", rows: asRows(settings) },
];
